import 'package:schedule_table/models/schedule.dart';



import '../models/schedule.dart';
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_calendar/calendar.dart';

class ScheduleData with ChangeNotifier {
  Schedule _schedule = Schedule(
      id: '1234',
      startDate: DateTime(2021, 9, 1),
      endDate: DateTime(2021, 9, 30),
      groupId: 'abcd',
      title: 'My Schedule',
      data: {
        'Batman': [
          Appointment(
            startTime: DateTime(2021, 9, 1, 10, 0, 0),
            endTime: DateTime(2021, 9, 1, 14, 0, 0),
            isAllDay: false,
            subject: 'Day',
            color: Colors.yellow[700] as Color,
            notes: 'DD',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 2, 10, 0, 0),
            endTime: DateTime(2021, 9, 2, 14, 0, 0),
            isAllDay: false,
            subject: 'Day',
            color: Colors.yellow[700] as Color,
            notes: 'DD',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 28, 10, 0, 0),
            endTime: DateTime(2021, 9, 28, 14, 0, 0),
            isAllDay: false,
            subject: 'Day',
            color: Colors.yellow[700] as Color,
            notes: 'DD',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 26, 0, 0, 0),
            endTime: DateTime(2021, 9, 27, 0, 0, 0),
            isAllDay: true,
            subject: 'Leave',
            color: Colors.green,
            notes: 'LV',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 27, 20, 0, 0),
            endTime: DateTime(2021, 9, 28, 08, 0, 0),
            isAllDay: false,
            subject: 'Night',
            color: Colors.purple,
            notes: 'NN',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 28, 14, 0, 0),
            endTime: DateTime(2021, 9, 28, 20, 0, 0),
            isAllDay: false,
            subject: 'Afternoon',
            color: Colors.purple,
            notes: 'AF',
            startTimeZone: '',
            endTimeZone: '',
          ),
        ],
        'SuperMan': [
          Appointment(
            startTime: DateTime(2021, 9, 3, 10, 0, 0),
            endTime: DateTime(2021, 9, 3, 14, 0, 0),
            isAllDay: false,
            subject: 'Day',
            color: Colors.yellow[700] as Color,
            notes: 'DD',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 4, 10, 0, 0),
            endTime: DateTime(2021, 9, 4, 14, 0, 0),
            isAllDay: false,
            subject: 'Day',
            color: Colors.yellow[700] as Color,
            notes: 'DD',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 21, 10, 0, 0),
            endTime: DateTime(2021, 9, 21, 14, 0, 0),
            isAllDay: false,
            subject: 'Day',
            color: Colors.yellow[700] as Color,
            notes: 'DD',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 25, 0, 0, 0),
            endTime: DateTime(2021, 9, 26, 0, 0, 0),
            isAllDay: true,
            subject: 'Leave',
            color: Colors.green,
            notes: 'LV',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 15, 20, 0, 0),
            endTime: DateTime(2021, 9, 16, 08, 0, 0),
            isAllDay: false,
            subject: 'Night',
            color: Colors.purple,
            notes: 'NN',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 16, 14, 0, 0),
            endTime: DateTime(2021, 9, 16, 20, 0, 0),
            isAllDay: false,
            subject: 'Afternoon',
            color: Colors.purple,
            notes: 'AF',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 12, 14, 0, 0),
            endTime: DateTime(2021, 9, 12, 20, 0, 0),
            isAllDay: false,
            subject: 'Afternoon',
            color: Colors.purple,
            notes: 'AF',
            startTimeZone: '',
            endTimeZone: '',
          ),
        ],
        'AntMan': [
          Appointment(
            startTime: DateTime(2021, 9, 24, 10, 0, 0),
            endTime: DateTime(2021, 9, 24, 14, 0, 0),
            isAllDay: false,
            subject: 'Day',
            color: Colors.yellow[700] as Color,
            notes: 'DD',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 25, 10, 0, 0),
            endTime: DateTime(2021, 9, 25, 14, 0, 0),
            isAllDay: false,
            subject: 'Day',
            color: Colors.yellow[700] as Color,
            notes: 'DD',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 21, 10, 0, 0),
            endTime: DateTime(2021, 9, 21, 14, 0, 0),
            isAllDay: false,
            subject: 'Day',
            color: Colors.yellow[700] as Color,
            notes: 'DD',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 15, 0, 0, 0),
            endTime: DateTime(2021, 9, 16, 0, 0, 0),
            isAllDay: true,
            subject: 'Leave',
            color: Colors.green,
            notes: 'LV',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 1, 20, 0, 0),
            endTime: DateTime(2021, 9, 2, 08, 0, 0),
            isAllDay: false,
            subject: 'Night',
            color: Colors.purple,
            notes: 'NN',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 2, 14, 0, 0),
            endTime: DateTime(2021, 9, 2, 20, 0, 0),
            isAllDay: false,
            subject: 'Afternoon',
            color: Colors.purple,
            notes: 'AF',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 3, 14, 0, 0),
            endTime: DateTime(2021, 9, 3, 20, 0, 0),
            isAllDay: false,
            subject: 'Afternoon',
            color: Colors.purple,
            notes: 'AF',
            startTimeZone: '',
            endTimeZone: '',
          ),
          Appointment(
            startTime: DateTime(2021, 9, 6, 14, 0, 0),
            endTime: DateTime(2021, 9, 6, 20, 0, 0),
            isAllDay: false,
            subject: 'Afternoon',
            color: Colors.purple,
            notes: 'AF',
            startTimeZone: '',
            endTimeZone: '',
          ),
        ],
      });

  Schedule get schedule {
    return _schedule;
  }
}

ScheduleData().Schedule;